version: "3"
services:
  api:
    build: ./services/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: inventory-api
  client:
    build: ./services/client
    ports:
      - "80:80"
    container_name: inventory-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: inventory-db